### ISSUE TITLE
Ausblenden v. einzelnen Veranstaltungen

### ISSUE THREAD

**Issue by ghost** [davidgengenbach/tucan-catalog#1]
Es wäre praktisch, wenn man einzelne Veranstaltungen ausblenden könnte. z.B. weil kein Interesse oder bereits gehört. Wieder-Einblenden könnte man dann beispielsweise über einen Button, der alle ausgeblendeten Veranstaltungen wieder einblendet, lösen.

**Comment by davidgengenbach** [comment]
Danke für die Anregung!

Ist eingebaut:
![screen shot 2016-04-09 at 20 10 56](https://cloud.githubusercontent.com/assets/2621491/14405426/3d8c0304-fe8f-11e5-8e84-9f01aa6168cb.png)

Die ausgeblendeten Kurse werden im Localstorage gespeichert und bleiben damit auch nach Neuladen ausgeblendet. Das gleiche funktioniert jetzt auch für Kurskategorien - einfach z.B. auf "Grundstudium" klicken.

[VV](http://davidgengenbach.de/informatik-vv/sose16)

**Comment by ghost** [comment]
Danke, das ging ja flott! :-)
