### ISSUE TITLE
Export module times in a machine-readable format

### ISSUE THREAD

**Issue by flokli** [davidgengenbach/tucan-catalog#2]
Currently, event data seems to be inside the html payload of a module.

Export it in a machine-readable format instead, and then pipe it to something like [this](https://github.com/adamgibbons/ics) to generate ical files on the fly on the client side.

**Comment by davidgengenbach** [comment]
Thanks for suggestion! It would be quite useful. Unfortunately I am very busy at the moment and will not be able to implement the functionality myself.

But if you are up for it, the change should not be that hard to implement, see [vv_exporter.py](https://github.com/davidgengenbach/tucan-tools/blob/master/vv_exporter.py#L64).
It should be a matter of iterating on the rows of the table.

**Comment by flokli** [comment]
So far, I did not really take a look at the code, let alone run it. I might tinker around with it.

**Comment by davidgengenbach** [comment]
Ah, one addition: you could also just use the end-product (`modules.json` with the course data in it) to extract the event data by yourself. Here is a sample `modules.json` (Crawled: 01.9.17):
[modules.json.zip](https://github.com/davidgengenbach/tucan-catalog/files/1271589/modules.json.zip)

**Comment by flokli** [comment]
I don't see myself finding time to tinker with it anytime soon, so I'll close this issue for now.
