### ISSUE TITLE
Falsche Dependencies?

### ISSUE THREAD

**Issue by pkwagner** [davidgengenbach/tucan-catalog#3]
Der in der README vorgeschlagene Workflow `Clone -> bower install` scheint derzeit nicht zu funktionieren (es treten diverse interne Fehler auf, Angular initialisiert erst gar nicht richtig) - möglicherweise gibt es da ein Problem mit den Dependencies?

Falls das adhoc unfixable ist, würde ich auch über einen verlinkten Tarball mit Libs-Folder als Workaround freuen :)

**Comment by davidgengenbach** [comment]
Ich habe den Workflow gerade eben nochmal mit einem frisch geclonten Repo versucht: hat ohne Probleme geklappt.

Der dritte Schritt (einen Webserver starten, zB. mit `http-server -o`) ist wichtig: sonst gibt es Probleme beim Nachladen der `modules.json` (cross-origin).
Falls es danach immer noch nicht klappt, kannst du mir bitte die Console Logs hier mitschicken?

EDIT: Falls es doch nicht klappt, hier ist ne ZIP mit allen Dependencies:
[tucan-catalog.zip](https://github.com/tucanlib/tucan-catalog/files/2384712/tucan-catalog.zip)

**Comment by pkwagner** [comment]
Ich habs nochmal mit einem regulären Apache statt http-server versucht, auch hier die selbe Problematik. Alle Libs werden richtig geladen, die Meldung in der Developer Console ist `TypeError: undefined is not a function (near '...s,s.document)}).info({angularVersion:"1....')`.

Sieht für mich sehr sehr kryptisch aus, von daher tippe ich wirklich mal auf einen internen Fehler in Angular. Vielleicht resolved bower bei mir auch einfach nur sehr sehr seltsam.

Wie dem auch sei, danke für die ZIP! Ich setze das Issue hier mal auf closed, das Problem scheint dann ja doch auf meiner Seite zu liegen :/

**Comment by davidgengenbach** [comment]
Ja, wie ich gerade gesehen habe, habe ich die Versionen der Dependencies nicht explizit festgelegt in der `bower.json` (das Projekt ist etwas älter). Kann sein, dass bei dir andere Versionen aufgelöst wurden als bei mir. Ich habe die Versionen jetzt festgelegt und gepusht. Kannst du's eventuell nochmal testen?

**Comment by pkwagner** [comment]
Jetzt läuft auch alles mit der regulären Installation perfekt, danke!
